/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.markusf.shout.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Shout service. Represents a row in the &quot;Shout_Shout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link de.markusf.shout.model.impl.ShoutModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link de.markusf.shout.model.impl.ShoutImpl}.
 * </p>
 *
 * @author Markus Feindler
 * @see Shout
 * @see de.markusf.shout.model.impl.ShoutImpl
 * @see de.markusf.shout.model.impl.ShoutModelImpl
 * @generated
 */
public interface ShoutModel extends BaseModel<Shout> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shout model instance should use the {@link Shout} interface instead.
	 */

	/**
	 * Returns the primary key of this shout.
	 *
	 * @return the primary key of this shout
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this shout.
	 *
	 * @param primaryKey the primary key of this shout
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the shout ID of this shout.
	 *
	 * @return the shout ID of this shout
	 */
	public long getShoutId();

	/**
	 * Sets the shout ID of this shout.
	 *
	 * @param shoutId the shout ID of this shout
	 */
	public void setShoutId(long shoutId);

	/**
	 * Returns the sender ID of this shout.
	 *
	 * @return the sender ID of this shout
	 */
	public long getSenderId();

	/**
	 * Sets the sender ID of this shout.
	 *
	 * @param senderId the sender ID of this shout
	 */
	public void setSenderId(long senderId);

	/**
	 * Returns the scope ID of this shout.
	 *
	 * @return the scope ID of this shout
	 */
	public long getScopeId();

	/**
	 * Sets the scope ID of this shout.
	 *
	 * @param scopeId the scope ID of this shout
	 */
	public void setScopeId(long scopeId);

	/**
	 * Returns the publish date of this shout.
	 *
	 * @return the publish date of this shout
	 */
	public Date getPublishDate();

	/**
	 * Sets the publish date of this shout.
	 *
	 * @param publishDate the publish date of this shout
	 */
	public void setPublishDate(Date publishDate);

	/**
	 * Returns the message of this shout.
	 *
	 * @return the message of this shout
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this shout.
	 *
	 * @param message the message of this shout
	 */
	public void setMessage(String message);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Shout shout);

	public int hashCode();

	public CacheModel<Shout> toCacheModel();

	public Shout toEscapedModel();

	public String toString();

	public String toXmlString();
}